### ISSUE TITLE
No response after inputing Session Key

### ISSUE THREAD

**Issue by sjtuli** [mbroton/chatgpt-api#15] opened 2022-12-09 02:23 UTC
<img width="1213" alt="截屏2022-12-09 10 15 55" src="https://user-images.githubusercontent.com/75962592/206608755-f7a75f5f-ea8b-4544-a18d-9572d2d818cb.png">
following this guide, I setup this project and  input the Session Key. But I can not type Enter in this interface.
While using another project, acheong08/ChatGPT), there is no similar circumstance. So I think the reason is not the Great wall of web.

**Comment by sjtuli** [comment] 2022-12-09 02:35
Api is OK

**Comment by mbroton** [comment] 2022-12-09 10:30
Hi @sjtuli!
Did you try to run this outside PyCharm? Directly in the OS terminal?
I can't reproduce this error.
`setup` command is only creating a text file, it's not connecting anywhere, so It has nothing to do with network.
I would say that probably this behavior comes from the terminal.
The acheong08/ChatGPT is not accepting session key in CLI, it expects from you to create this file, as far as I see, so It's not a case.

We are going to have functionality of passing the config file to `chatgpt-api` in a day or so awell.
As a workaround, you can manually create a text file in `/Users/li/.config/chatgpt_api/key.txt` and paste session key there.
I'm sorry for the inconvenience.

**Comment by OblackatO** [comment] 2022-12-09 16:20
@mbroton I just need to fix three tests and I will open a merge request. We basically already have that functionality. The tests don't pass because the config directory changed *(I generalized it for both logging and session key stuff)*

I'll fix the tests when I have time. In the weekend I should pop up something.

**Comment by OblackatO** [comment] 2022-12-09 23:55
@sjtuli Are you using MacOS? If yes, the integrated terminal in Pycharm is probably ZSH, which limits the input length. This is also the case in some other Unix operating systems. 

FYI: You cannot type enter, because the limit to maximum characters is reached. Delete one, and press enter and it should work.

**Comment by mbroton** [comment] 2022-12-14 11:17
I just merged a PR by @OblackatO: https://github.com/mbroton/chatgpt-api/pull/16
which makes subject of this issue no longer valid.
Thanks @OblackatO for help! 🍰

**Closed by mbroton** 2022-12-14 11:17 UTC
