### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by sudarsun** [mbroton/chatgpt-api#23] opened 2023-01-09 11:29 UTC
While running "chatgpt setup" from the command line, the following error is reported by Python 3.8 / Ubuntu 20.04.5
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

upon replacing the multiple types "str | None" with Union[str, None], the error goes away.  The replacement has to be done at chatgpt/{api, cli, payloads}.py

**Comment by rvjenya** [comment] 2023-01-12 14:18
Any solutions?

**Comment by mbroton** [comment] 2023-01-12 14:24
Hi! It's a duplicate of #22

**Closed by mbroton** 2023-01-12 14:24 UTC

**Comment by sudarsun** [comment] 2023-01-12 15:17
The error goes away after replacing the multiple types "str | None" with Union[str, None]. 
The replacement has to be done at chatgpt/{api, cli, payloads}.py
